### ISSUE TITLE
I'm obviously being stupid, but how do I install these templates?

### ISSUE THREAD

**Issue by claudemuller** [deviantfero/wpgtk-templates#11]
Great work! Really impressed :)

I'm obviously being stupid, but how do I install these templates?

Particularly the bspwm one?

`wpg-install.sh -H <hash>`

Hash of what? Could you please give me an example?

Thanks,

**Comment by deviantfero** [comment]
sorry for being late, hope you were able to figure it out on your own, `-H` is to pass a specific commit from which you want to clone configuration, it is to use previous versions of templates in case you need them, this is optional and you will most likely not need it, in order to install templates you just combine the flags of the ones you want, for example

```
wpg -ibp
```

will install the icon set, the bspwm template and the polybar template, keep in mind some of these will override your configurations (such as the polybar one), but it will make a backup of your current config.

**Comment by claudemuller** [comment]
Hmm.. when I ran the script before the usage info didn't show a bspwm option. Now that I ran it without any options and it seemed to do a fresh pull the option is there.. So I don't need the -H option (at least in my mind). Thanks anyway :)

**Comment by deviantfero** [comment]
yeah, that's correct, unless you want previous versions of the templates installed, the -H flag has no use.
