### ISSUE TITLE
Rebase FlatColor on Vimix GTK Theme.

### ISSUE THREAD

**Issue by b1scu1t** [deviantfero/wpgtk-templates#14]
The current FlatColor theme seem to have bad compatibility with multiple DEs like Mate and Xfce. The GTK2 themes also fare poorly as widgets are occasionally glitchy, missing or invisible in GTK2 applications and Qt5 (via qt5-styleplugin).

I suspect that the problems stem from the 'Polar Night' base, that was explicitly developed for GNOME only, and it seems abandoned as the last commit was over two years ago.

I propose [Vimix](https://github.com/vinceliuice/vimix-gtk-themes) GTK theme. 
Quoting the repo: "Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, XFCE, Mate, etc."

If its not possible, can you provide tips or advice as to how I can make the theme compatible with `wpgtk`?

**Comment by deviantfero** [comment]
It needs to not be built with a css framework like sass or less, because we can't be building the theme each time we want to make a change, that would make it useless in our use-case.

what we need is a theme that extracts all it's colors as variables in a single file using pure css variables, like in `gtk.css` of the current theme

I think it would be easier if we can fix those incompatibilities with Mate and XFCE in this theme

**Comment by b1scu1t** [comment]
OK, I understand.
Since the like of Vimix and Oomox use those frameworks, it would take a lot more processing power for a single change, thereby defeating the point of `wpgtk`.

I'll close the issue.

So we'll focus on polishing FlatColor?
